version: '3.8'

services:
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: reservas_db
    volumes:
      - pgdata2:/var/lib/postgresql/data
      # Vamos a comentar esta línea temporalmente con un '#' para evitar que rompa el inicio
      # - ./backend/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      # Simplificamos el comando quitando los símbolos de dólar
      test: ["CMD-SHELL", "pg_isready -U postgres -d reservas_db"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  pgdata2:
